export type IncomeSubcategory =
| 'Salary'
| 'Military Pay'
| 'Contractor Income'
| 'Gig Work'
| 'Rental Income'
| 'Dividends'
| 'Interest'
| 'Child Support'
| 'Disability Income'
| 'Pension'
| 'Unemployment Benefits'
| 'Tax Refund'
| 'Other Income'

export type ExpenseSubcategory =
| 'Other'
| 'Tobacco & Vape'
| 'Donations'
| 'Postage & Shipping'
| 'Storage'
| 'Other Services'
| 'Other Government/Nonprofit'
| 'Books & News'
| 'Clothing & Accessories'
| 'Convenience Stores'
| 'Department Stores'
| 'Discount Stores'
| 'Electronics'
| 'Gifts & Novelties'
| 'Office Supplies'
| 'Online Marketplaces'
| 'Sporting Goods'
| 'Superstores'
| 'Other Merchandise'
| 'Gambling'
| 'Music & Audio'
| 'Events & Attractions'
| 'TV & Movies'
| 'Video Games'
| 'Other Entertainment'
| 'Student Loan Payment'
| 'Pet Supplies'
| 'Education Services'
| 'Childcare'
| 'Dental Care'
| 'Eye Care'
| 'Nursing Care'
| 'Pharmacy & Supplements'
| 'Primary Care'
| 'Veterinary Services'
| 'Other Medical'
| 'Fitness'
| 'Hair & Beauty'
| 'Laundry & Dry Cleaning'
| 'Other Personal Care'
| 'Accounting & Financial Planning'
| 'ATM Fees'
| 'Insufficient Funds Fee'
| 'Interest Charge'
| 'Foreign Transaction Fee'
| 'Overdraft Fee'
| 'Late Fee'
| 'Cash Advance Fee'
| 'Other Bank Fees'
| 'Consulting & Legal'
| 'Government Services'
| 'Car Payment'
| 'Bikes & Scooters'
| 'Gas'
| 'Parking'
| 'Transit'
| 'Ride Share'
| 'Tolls'
| 'Transportation'
| 'Automotive'
| 'Insurance'
| 'Groceries'
| 'Alcohol'
| 'Gas & Electric'
| 'Internet & Cable'
| 'Waste'
| 'Phone'
| 'Water'
| 'Utilities'
| 'Flights'
| 'Lodging'
| 'Rental Car'
| 'Travel'
| 'Coffee'
| 'Fast Food'
| 'Restaurant'
| 'Vending'
| 'Food & Drink'
| 'Rent'
| 'Furniture'
| 'Hardware'
| 'Repairs'
| 'Security'
| 'Home Improvement'
| 'Mortgage'

export type TransferSubcategory =
| 'Auto Loan Disbursement'
| 'Cash Advance Disbursement'
| 'Earned Wage Access Disbursement'
| 'Mortgage Disbursement'
| 'Personal Loan Disbursement'
| 'Student Loan Disbursement'
| 'Other Loan Disbursement'
| 'Buy Now Pay Later Payment'
| 'Cash Advance Payment'
| 'Credit Card Payment'
| 'Earned Wage Access Repayment'
| 'Personal Loan Payment'
| 'Other Loan Payment'
| 'Account Transfer In'
| 'Cash Deposit' 
| 'Investment Transfer In'
| 'Savings Transfer In'
| 'App Transfer In'
| 'Incoming Wire'
| 'Other Transfer In'
| 'Account Transfer Out'
| 'Crypto Transfer Out'
| 'Investment Transfer Out'
| 'Savings Transfer Out'
| 'App Transfer Out'
| 'Outgoing Wire'
| 'Cash Withdrawal'
| 'Other Transfer Out'
| 'Tax Payment'

export type Subcategory =
  | ExpenseSubcategory
  | IncomeSubcategory
  | TransferSubcategory;
