import { Category } from '../../types/categories';
import { Subcategory } from '../../types/subcategories';

export const SUBSCRIPTION_MERCHANTS = [

"Netflix",
    "Hulu",
    "Disney+",
    "HBO Max",
    "Max",
    "Amazon Prime Video",
    "Apple TV+",
    "Paramount+",
    "Peacock",
    "YouTube Premium",
    "Crunchyroll",
    "Funimation",
    "Sling TV",
    "FuboTV",
    "Philo",
    "Starz",
    "Showtime",
    "AMC+",
    "BritBox",
    "Acorn TV",
    "CuriosityStream",
    "Discovery+",

    "Spotify",
    "Apple Music",
    "YouTube Music",
    "Pandora",
    "Tidal",
    "SiriusXM",
    "Audible",
    "Amazon Music Unlimited",
    "SoundCloud Go",

    "iCloud",
    "Google One",
    "Dropbox",
    "OneDrive",
    "Box",
    "Mega",
    "Backblaze",
    "Carbonite",

    "Adobe Creative Cloud",
    "Microsoft 365",
    "Notion",
    "Evernote",
    "Todoist",
    "Grammarly",
    "Figma",
    "Canva",
    "GitHub",
    "Atlassian",
    "JetBrains",
    "1Password",
    "LastPass",
    "Dashlane",
    "Quicken",
    "QuickBooks Online",
    "FreshBooks",
    "TurboTax Live",
    "Mailchimp",
    "Squarespace",
    "Wix",
    "Shopify",
    "Webflow",
    "Zoom",
    "Slack",
    "Asana",
    "Monday.com",
    "Trello Premium",
    "HubSpot",
    "Calendly",
    "Typeform",
    "SurveyMonkey",

    "ChatGPT",
    "OpenAI",
    "Claude",
    "Anthropic",
    "Perplexity",
    "Midjourney",
    "RunwayML",
    "ElevenLabs",
    "Replit",
    "Cursor AI",
    "Jasper AI",
    "Copy.ai",
    "Writesonic",

    "Peloton",
    "Planet Fitness",
    "LA Fitness",
    "Anytime Fitness",
    "Crunch Fitness",
    "Orangetheory",
    "lifetime fitness",
    "Equinox",
    "ClassPass",
    "WW",
    "Noom",
    "Calm",
    "Headspace",
    "MyFitnessPal Premium",
    "Fitbit Premium",
    "Whoop",
    "Tonal",
    "Fitbod",
    "Strava Premium",
    "Alo Moves",
    "Down Dog",

    "HelloFresh",
    "Blue Apron",
    "Home Chef",
    "EveryPlate",
    "Factor",
    "Green Chef",
    "Freshly",
    "Daily Harvest",
    "ButcherBox",
    "Misfits Market",
    "Thrive Market",

    "BarkBox",
    "KitNipBox",
    "Chewy Autoship",

    "Stitch Fix",
    "Rent the Runway",
    "Nuuly",
    "Le Tote",
    "Fabletics",
    "Savage X Fenty",
    "Trunk Club (legacy)",

    "Birchbox",
    "Ipsy",
    "BoxyCharm",
    "Scentbird",
    "GlossyBox",
    "FabFitFun",
    "Allure Beauty Box",

    "KiwiCo",
    "Lovevery",
    "Little Passports",

    "The New York Times",
    "NYT Games",
    "NYT Cooking",
    "The Wall Street Journal",
    "The Washington Post",
    "Bloomberg",
    "The Economist",
    "Financial Times",
    "Medium",
    "Substack",
    "Patreon",
    "Scribd",

    "Tinder",
    "Bumble",
    "Hinge",
    "Match.com",
    "eHarmony",
    "OkCupid",
    "Plenty of Fish",

    "Xbox Game Pass",
    "PlayStation Plus",
    "Nintendo Switch Online",
    "EA Play",
    "Roblox Premium",
    "Minecraft Realms",
    "Twitch Subscriptions",
    "RuneScape Membership",
    "World of Warcraft Subscription",

    "AAA Membership",
    "Costco Membership",
    "Sam's Club Membership",
    "Amazon Prime",

    "Ancestry.com",
    "23andMe+",
    "MyHeritage",

    "Duolingo Plus",
    "Coursera Plus",
    "MasterClass",
    "Skillshare",
    "Brilliant",
    "Codecademy Pro",
    "Udemy Pro",
    "Reforge",

    "LifeLock",
    "Identity Guard",
    "Experian",
    "Equifax Complete",
    "TransUnion TrueIdentity",
    "Aura",
    "Norton",
    "McAfee",
    "NordVPN",
    "ExpressVPN",
    "Surfshark",

    "Uber One",
    "Lyft Pink",
    "Zipcar",
    "Turo Go",

    "Ring Protect",
    "Nest Aware",
    "ADT",
    "SimpliSafe",

    "Hims",
    "Hers",
    "Roman",
    "Keeps",

    "Hello Bello",
    "The Honest Company",

    "Blinkist",
    "Headway",

    "Wine Awesomeness",
    "Winc",
    "Firstleaf",
    "Naked Wines",
    "Vinebox",

    "Bespoke Post",
    "BattlBox",
    "Loot Crate",
    "Bark Super Chewer",

    "Plex Pass",
    "Vimeo Premium",

    "DocuSign",
    "HelloSign",

    "Mint Mobile (monthly plan)",
    "Visible Wireless",
    "Google Fi",
    "Ting Mobile",
    "Republic Wireless",
    
    "DashPass",
    "DoorDash",
    "Uber One",
    "Uber Eats",
    "Grubhub+",
    "Grubhub Plus",
    "Postmates Unlimited",
    "Caviar",

    "Instacart+",
    "Instacart",
    "Shipt",
    "Walmart+",
    "Walmart Plus",
    "Amazon Fresh",
    "Thrive Market",
    "Misfits Market",
    "Imperfect Foods",

    "Gobble",
    "Sunbasket",
    "Purple Carrot",
    "Territory Foods",

    "Winc",
    "Firstleaf",
    "Naked Wines",
    "Vinebox",
    "Bright Cellars",
    "WSJ Wine Club",
    "Martha Stewart Wine Club",
    "Gold Medal Wine Club",
    "Plonk Wine Club",

    "Frank And Oak Style Plan",
    "Wantable",
    "Dia & Co",

    "Kinder Beauty",
    "LookFantastic",
    "Macy's Beauty Box",

    "ChatGPT Plus",
    "ChatGPT Team",
    "Claude Pro",
    "Claude Team",
    "Perplexity Pro",
    "Synthesia",
    "Pika Labs"

];

export const PAYROLL_KEYWORDS = [

  'PAYROLL',
  'DIRECT DEP',
  'ADP',
  'GUSTO',
  'PAYCHEX',
  'SALARY',

];

export const TRANSFER_KEYWORDS = [

  'TRANSFER',
  'VENMO',
  'ZELLE',
  'CASH APP',
  'PAYPAL TRANSFER',

];

export const BILL_CATEGORIES = [

  'mortgage',
  'rent',
  'utilities',
  'insurance',
  'loan',
  'internet',
  'phone',
  'electric',
  'water',
  'gas',

];